--- !ClientConfig
storage_count: 3
default_chunk_size: 10
chunk_sizes : [10, 11, 12]  # If the size of the list is less than the storage
                            # count, then the default chunk size will backfill
                            # the remaining storage consumers.  If the size is
                            # greater than the storage count, then the list
                            # will be truncated.
runtime: 600
